# Site settings
title: Rob Harrop
email: rob.harrop@gmail.com
description: >
  Rob Harrop, CTO @ Skipjaq.
  Writing about coding, maths, distributed systems, performance
  optimisation and machine learning
baseurl: ""
url: "http://robharrop.github.io"
date_format: "%b %-d, %Y"

# Social settings
show_social_icons: true
twitter_username: robertharrop
github_username:  robharrop

# Text
text:
  index:
    coming_soon: Coming soon!

# Build settings
markdown: kramdown
paginate: 5
gems:
  - jekyll-paginate
