# Site settings
title: Rob Harrop
email: rob.harrop@gmail.com
description: >
  Rob Harrop, CTO @ <a href="http://www.skipjaq.com">Skipjaq</a>.
  Writing about coding, maths, distributed systems, performance 
  optimisation and machine learning.
baseurl: ""
url: "http://robharrop.github.io"
twitter_username: robertharrop
github_username:  robharrop

# Build settings
markdown: kramdown
